name: Deploy Infrastructure

on:
  push:
    branches:
      - main 
jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    